spring:
  application:
    name: TelegramWeatherBot
  config:
    import: optional:file:.env[.properties]
  messages:
    basename: messages
    encoding: UTF-8
  cache:
    type: redis
    cache-names: redis-cache
    redis:
      time-to-live: 60m
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DATABASE}?currentSchema=${POSTGRES_SCHEMA}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db/db.changelog-master.yaml
    default-schema: weather
    enabled: true
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        hbm2ddl.auto: validate
    open-in-view: false

telegram:
  name: ${BOT_NAME}
  token: ${BOT_KEY}

weather:
  token: ${WEATHER_API_KEY}
  base-url: ${BASE_WEATHER_URL}
  weather-url: ${WEATHER_URL}
  city-url: ${CITY_URL}